### ISSUE TITLE
coveralls

### ISSUE THREAD

**Issue by mikemorris** [mapbox/node-mapbox-gl-native#105]
Add Coveralls support for test coverage reports. See https://github.com/mapbox/node-fontnik/pull/79 for implementation.

**Comment by springmeyer** [comment]
Just sync'ed voice with @mikemorris on this. We are going to punt on this for now and return another day. The challenges are:

  - Can't run coverage on OS X since travis OS X machines have no gpu (or mesa software renderer equivalent that we know of)
  - Coverage is not viable yet with clang 3.4 on linux (we suspect because the clang is too old for the --coverage flag to work correctly)
  - But upgrading to clang/llvm 3.5 is not likely (untested) easy because mesa depends on llvm 3.4
  - We've tried to mason-package mesa against llvm 3.5 but hit problems @mikemorris may remember
  - Overall the mesa package has a lot of runtime deps that needs to be sudo installed: we should try to get them all [whitelisted with travis](http://docs.travis-ci.com/user/apt/] (most already are) so mesa will not need `sudo:required`, but that is a whole different push.

**Comment by mikemorris** [comment]
Should reopen a ticket in https://github.com/mapbox/mapbox-gl-native for adding Coveralls support for `node` platform builds.
