### ISSUE TITLE
Node.js v0.12.x binaries may be ABI-incompatible

### ISSUE THREAD

**Issue by mikemorris** [mapbox/node-mapbox-gl-native#137]
In Node.js v0.12.x **stable series** patch versions [v8 and libuv are being upgraded](https://nodejs.org/changelog.html) without incrementing `NODE_MODULE_VERSION`, breaking important assumptions in [node-pre-gyp](https://github.com/mapbox/node-pre-gyp). This may be causing binaries built on Node.js v0.12.0 to be ABI-incompatible with Node.js v0.12.4.

Details at https://github.com/joyent/node/issues/5789

/cc @springmeyer

**Comment by springmeyer** [comment]
@mikemorris I just tested running node-mapnik against node 0.12.4 that was built against node v0.12.2 and it worked fine. So, my first impression is that not bumping `NODE_MODULE_VERSION` for the node v0.12.x series up to 0.12.4 was correct. The `NODE_MODULE_VERSION` is designed to be bumped when the public ABI has seen an incompatible change. A version change in libuv or v8 does not necessary incur this even though it usually does.

So, you are seeing this error:

> libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: libuv version mismatch: headers report 1.0.2, but library reports 1.5.0

because of [this check](https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/util/uv.cpp#L21) rather than a proven ABI incompatibility. That is not to say that this is not possibly some lurking ABI incompatibility - but at least as this point I've not noticed one.
