### ISSUE TITLE
Error: libstdc++.so.6: version 'GLIBCXX_3.4.20' not found

### ISSUE THREAD

**Issue by bsudekum** [mapbox/node-mapbox-gl-native#138]
I'm getting the following error after installing the `node-mapbox-gl-native@1.1.1`:

```
Error: /home/travis/build/mapbox/api-gl/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/travis/build/mapbox/api-gl/node_modules/gl-maps/node_modules/tilelive-gl/node_modules/mapbox-gl-native/lib/mapbox-gl-native.node)
```
Link to [failed build can be found here](https://magnum.travis-ci.com/mapbox/api-gl/builds/12827381#L722).

/cc @mikemorris @jfirebaugh

**Comment by springmeyer** [comment]
The libstdc++ that is default on travis is too old to run node-mapbox-gl-native/c++11. That is a known. So the question is why you are hitting it. Perhaps the hack you are using of `if [[ $(uname -s) == 'Linux' ]]; then wget https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test/+files/libstdc%2B%2B6_4.8.1-2ubuntu1~12.04_amd64.deb && dpkg -x libstdc++6_4.8.1-2ubuntu1~12.04_amd64.deb ./ && export LD_PRELOAD=$(pwd)/usr/lib/x86_64-linux-gnu/libstdc++.so.6; fi` is failing. What you could do is try migrating to the `addons: apt` method of upgrading libstdc++ sudoless. See https://github.com/mapbox/node-mapbox-gl-native/blob/master/.travis.yml#L14-L17 for more details. I think what you would need for just using node-mgbl (rather than building it) is something like:

```
    addons:
      apt:
        sources: [ 'ubuntu-toolchain-r-test']
        packages: ['libstdc++6']
```

**Comment by mikemorris** [comment]
I'm guessing this is caused by the recent switch to C++14 in mbgl (which I moved node-mbgl to by switching to Travis' new Docker containers), while `.travis.yml` on api-gl is still configured for C++11 support on the old pre-Docker infrastructure.

**Comment by mikemorris** [comment]
[Added a note to the README](https://github.com/mapbox/node-mapbox-gl-native/commit/27fc2f18e30a92234b997cb6a16ce462821e5c5b) documenting that this requires C++14 runtime support, testing @springmeyer's suggestion in a downstream module seems to work perfectly.

**Comment by vicapow** [comment]
Here are the commands I ran to fix this for me:

````
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt-get install gcc-4.9
sudo apt-get upgrade libstdc++6
````

**Comment by vsharathchandra** [comment]
How to fix the above issue in centos?
